/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is normally auto-generated by `next dev` / `next build`.
// Do not edit it by hand — it is committed here only so the project has a
// valid baseline before the first `npm run dev`.
